// After Hours Cafe — Menu Data
const menuItems = [
  { id:1,  name:"Midnight Espresso",   category:"coffee",  emoji:"☕", price:180, desc:"Double shot, dark roast, intense & bold.",                popular:true  },
  { id:2,  name:"Velvet Latte",        category:"coffee",  emoji:"🥛", price:250, desc:"Silky steamed milk with a smooth espresso base.",         popular:true  },
  { id:3,  name:"Spiced Cappuccino",   category:"coffee",  emoji:"☕", price:230, desc:"Classic cappuccino with cardamom & cinnamon.",            popular:false },
  { id:4,  name:"Caramel Macchiato",   category:"coffee",  emoji:"🍯", price:270, desc:"Espresso layered with vanilla & buttery caramel.",        popular:true  },
  { id:5,  name:"Pour Over",           category:"coffee",  emoji:"🫗", price:220, desc:"Single origin, slow-poured — floral & complex.",          popular:false },
  { id:6,  name:"Americano",           category:"coffee",  emoji:"☕", price:160, desc:"Espresso shots diluted with hot water — clean.",           popular:false },
  { id:7,  name:"Cold Brew",           category:"cold",    emoji:"🧊", price:280, desc:"12-hour steeped cold brew, smooth and low-acid.",         popular:true  },
  { id:8,  name:"Iced Mocha",          category:"cold",    emoji:"🍫", price:300, desc:"Dark chocolate, espresso, milk & ice.",                   popular:true  },
  { id:9,  name:"Mango Cooler",        category:"cold",    emoji:"🥭", price:220, desc:"Fresh Nepalese mangoes blended with cold brew tea.",      popular:false },
  { id:10, name:"Strawberry Matcha",   category:"cold",    emoji:"🍓", price:290, desc:"Ceremonial matcha with fresh strawberry purée.",          popular:false },
  { id:11, name:"Iced Vanilla Latte",  category:"cold",    emoji:"🌿", price:260, desc:"Cold espresso, vanilla syrup & milk over ice.",           popular:false },
  { id:12, name:"Masala Chai",         category:"tea",     emoji:"🫖", price:150, desc:"Spiced milk tea with ginger, cardamom & black pepper.",   popular:true  },
  { id:13, name:"Himalayan Green",     category:"tea",     emoji:"🍵", price:160, desc:"Light loose-leaf green tea from the hills of Nepal.",     popular:false },
  { id:14, name:"Lavender Earl Grey",  category:"tea",     emoji:"💜", price:190, desc:"Classic Earl Grey elevated with dried lavender buds.",    popular:false },
  { id:15, name:"Avocado Toast",       category:"food",    emoji:"🥑", price:320, desc:"Sourdough, smashed avo, chilli flakes & tomatoes.",       popular:true  },
  { id:16, name:"Egg Croissant",       category:"food",    emoji:"🥐", price:280, desc:"Flaky butter croissant with scrambled egg & cheese.",     popular:false },
  { id:17, name:"Momo Basket",         category:"food",    emoji:"🥟", price:250, desc:"8 steamed momos with tomato achaar.",                     popular:true  },
  { id:18, name:"Grilled Sandwich",    category:"food",    emoji:"🥪", price:270, desc:"Pressed sandwich with veggies, cheese & pesto.",          popular:false },
  { id:19, name:"Banana Pancakes",     category:"food",    emoji:"🥞", price:240, desc:"Fluffy pancakes topped with banana & honey.",             popular:false },
  { id:20, name:"Mocha Lava Cake",     category:"dessert", emoji:"🎂", price:340, desc:"Warm chocolate lava cake with espresso-cream center.",    popular:true  },
  { id:21, name:"Tiramisu",            category:"dessert", emoji:"🍰", price:310, desc:"House-made tiramisu dusted with cocoa & espresso soak.",  popular:true  },
  { id:22, name:"Mango Cheesecake",    category:"dessert", emoji:"🥭", price:290, desc:"No-bake cheesecake with local mango compote.",            popular:false },
  { id:23, name:"Dark Brownie",        category:"dessert", emoji:"🍫", price:200, desc:"Fudgy 70% dark chocolate brownie, warm from the oven.",   popular:false },
];
